# Generated by Django 5.0.6 on 2024-07-15 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_personnel_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='picture',
        ),
        migrations.AddField(
            model_name='personnel',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='personnel_images/'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='contact',
            field=models.CharField(default='e.g. timezone.now', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personnel',
            name='location',
            field=models.CharField(default='timezone.now', max_length=100),
            preserve_default=False,
        ),
    ]
