# Generated by Django 5.1.2 on 2024-11-22 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_personnel_created_at_personnel_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='image',
            field=models.ImageField(blank=True, default='favicon.ico', null=True, upload_to='personnel_images/'),
        ),
    ]
