# Generated by Django 5.0.6 on 2024-11-28 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_archivedlogs_logs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logs',
            options={'verbose_name_plural': 'Logs'},
        ),
    ]
