# Generated by Django 5.1.3 on 2024-12-20 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_roomschedule_options_remove_roomschedule_date'),
        ('main', '0034_alter_personnel_employment_type'),
    ]

    operations = [
    ]
