# Generated by Django 5.1.3 on 2024-12-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_alter_roomschedule_date_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='roomschedule',
            name='start_time_before_end_time',
        ),
        migrations.RemoveConstraint(
            model_name='roomschedule',
            name='date_or_day_must_exist',
        ),
        migrations.AddField(
            model_name='roomschedule',
            name='schedule_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('temporary', 'Temporary')], default='regular', max_length=10),
        ),
        migrations.AlterField(
            model_name='roomschedule',
            name='class_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='roomschedule',
            name='professor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='roomschedule',
            name='section',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
