# Generated by Django 5.1.3 on 2025-01-04 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_remove_roomschedule_day_of_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomschedule',
            name='day_of_week',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default=2, max_length=10),
            preserve_default=False,
        ),
    ]
