# Generated by Django 5.1.3 on 2025-01-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_alter_roomschedule_professor_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomschedule',
            name='professor_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='roomschedule',
            name='section_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='roomschedule',
            name='subject_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
