# Generated by Django 5.1.4 on 2025-01-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0067_remove_roomschedule_unique_schedule_per_time_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedRoomScheduleLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('room_name', models.CharField(max_length=255)),
                ('schedule_type', models.CharField(choices=[('regular', 'Regular'), ('temporary', 'Temporary')], max_length=10)),
                ('timestamp', models.DateTimeField()),
                ('archived_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomScheduleLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('room_name', models.CharField(max_length=255)),
                ('schedule_type', models.CharField(choices=[('regular', 'Regular'), ('temporary', 'Temporary')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Room Schedule Logs',
            },
        ),
    ]
