services:
  - type: web
    name: infosko
    env: python
    plan: free
    buildCommand: ""
    startCommand: gunicorn INFOSKOProject.infosko.wsgi:application --bind 0.0.0.0:8000
    staticPublishPath: media
    dockerfilePath: ./Dockerfile
