# Generated by Django 5.0.6 on 2024-09-21 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_roomschedule_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='isOccupied',
            new_name='occupied',
        ),
    ]
