# Generated by Django 5.1.2 on 2024-11-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_personnel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='image',
            field=models.ImageField(blank=True, default='media/defaultpic.jpg', null=True, upload_to='personnel_images/'),
        ),
    ]
