# Generated by Django 5.1.3 on 2024-12-25 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_rename_supervisor_roomschedule_professor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TemporaryPersonnel',
        ),
        migrations.RenameField(
            model_name='roomschedule',
            old_name='time_end',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='roomschedule',
            old_name='time_start',
            new_name='start_time',
        ),
        migrations.AlterField(
            model_name='roomschedule',
            name='class_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='roomschedule',
            name='day_of_week',
            field=models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='roomschedule',
            name='professor',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='roomschedule',
            name='section',
            field=models.CharField(max_length=255),
        ),
    ]
