# Generated by Django 5.1.3 on 2024-12-31 00:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_remove_room_date_remove_room_day_of_week_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomschedule',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='roomschedule',
            name='professor',
        ),
        migrations.RemoveField(
            model_name='roomschedule',
            name='schedule_type',
        ),
        migrations.RemoveField(
            model_name='roomschedule',
            name='section',
        ),
        migrations.AlterField(
            model_name='roomschedule',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roomschedule',
            name='day_of_week',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roomschedule',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.room'),
        ),
    ]
