# Generated by Django 5.0.6 on 2024-09-23 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_personnel_employment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='employment_type',
            field=models.CharField(choices=[('full-time', 'Full-Time'), ('part-time', 'Part-Time'), ('Key-Person', 'Key-Person')], default='Key-Person', max_length=10),
        ),
    ]
