# Generated by Django 5.0.6 on 2024-09-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_personnel_employment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='employment_type',
            field=models.CharField(choices=[('full-time', 'Full-Time'), ('part-time', 'Part-Time'), ('key-person', 'Key-Person')], default='key-person', max_length=10),
        ),
    ]
