# Generated by Django 5.1.2 on 2024-10-30 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_remove_personnel_university_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='university_position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='employment_type',
            field=models.CharField(choices=[('select', 'Select'), ('full-time', 'Full-Time'), ('part-time', 'Part-Time'), ('key-person', 'Key Person')], max_length=50),
        ),
    ]
