# Generated by Django 5.1.3 on 2024-12-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_remove_roomschedule_start_time_before_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='day_of_week',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
