# Generated by Django 5.1.3 on 2024-12-30 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_alter_room_last_checked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='date',
        ),
        migrations.RemoveField(
            model_name='room',
            name='day_of_week',
        ),
        migrations.AlterField(
            model_name='room',
            name='last_checked',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='roomschedule',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='main.room'),
        ),
    ]
