# Generated by Django 5.1.4 on 2025-01-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0064_alter_semester_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='roomschedule',
            constraint=models.UniqueConstraint(fields=('room', 'date', 'start_time', 'end_time'), name='unique_schedule_per_time'),
        ),
    ]
