# Generated by Django 5.0.6 on 2024-07-10 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personnel',
            old_name='location',
            new_name='role',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='information',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='picture',
        ),
        migrations.AddField(
            model_name='personnel',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to='personnel_photos/'),
        ),
    ]
