# Generated by Django 5.0.6 on 2024-07-11 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_location_personnel_role_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personnel',
            old_name='role',
            new_name='position',
        ),
        migrations.AddField(
            model_name='personnel',
            name='contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personnel',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personnel',
            name='picture',
            field=models.ImageField(default='N/A', upload_to='personnel_pics'),
            preserve_default=False,
        ),
    ]
