# Generated by Django 5.0.6 on 2024-07-11 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_role_personnel_position_personnel_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='photo',
        ),
    ]
