# Generated by Django 5.0.6 on 2024-07-12 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_personnel_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='personnel_pics'),
        ),
    ]
