# Generated by Django 5.0.6 on 2024-07-15 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_personnel_picture_personnel_images_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personnel',
            old_name='images',
            new_name='image',
        ),
    ]
