# Generated by Django 5.0.6 on 2024-09-22 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_isoccupied_room_occupied'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='employment_type',
            field=models.CharField(choices=[('full-time', 'Full-Time'), ('part-time', 'Part-Time')], default='full-time', max_length=10),
        ),
    ]
