# Generated by Django 5.0.6 on 2024-09-22 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_personnel_employment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='employment_type',
            field=models.CharField(choices=[('full-time', 'Full-Time'), ('part-time', 'Part-Time'), ('N/A', 'N/A')], default='N/A', max_length=10),
        ),
    ]
