# Generated by Django 5.0.6 on 2024-10-21 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_personnel_employment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='university_position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
