# Generated by Django 5.0.6 on 2024-10-24 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_personnel_university_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='employment_type',
            field=models.CharField(choices=[('select', 'Select'), ('full-time', 'Full-Time'), ('part-time', 'Part-Time'), ('key-person', 'Key Person')], max_length=50),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='university_position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
