# Generated by Django 5.1.2 on 2024-10-29 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_rename_department_position_personnel_university_position_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='university_position',
        ),
        migrations.AlterField(
            model_name='personnel',
            name='employment_type',
            field=models.CharField(choices=[('select', 'Select'), ('full-time', 'Full-Time'), ('part-time', 'Part-Time'), ('key-person', 'Key Person')], default='select', max_length=10),
        ),
    ]
