# Generated by Django 5.1.2 on 2024-11-22 07:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_rename_university_position_personnel_department_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personnel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='employment_type',
            field=models.CharField(choices=[('select', 'Select'), ('full-time', 'Full-Time'), ('part-time', 'Part-Time'), ('key-person', 'Key Person')], default='select', max_length=50),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='image',
            field=models.ImageField(blank=True, default='default_image.png', null=True, upload_to='personnel_images/'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
