# Generated by Django 5.1.2 on 2024-11-22 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_personnel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='image',
            field=models.ImageField(blank=True, default='default.pic', null=True, upload_to='personnel_images/'),
        ),
    ]
