# Generated by Django 5.0.7 on 2024-12-04 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_personnel_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomschedule',
            options={'verbose_name_plural': 'Room Schedules'},
        ),
        migrations.RemoveField(
            model_name='roomschedule',
            name='date',
        ),
    ]
