# Generated by Django 5.1.3 on 2024-12-15 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_temporarypersonnel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='employment_type',
            field=models.CharField(choices=[('select', 'Select'), ('full-time', 'full-time'), ('part-time', 'part-time'), ('key-person', 'key-person')], default='select', max_length=50),
        ),
    ]
