# Generated by Django 5.1.3 on 2024-12-22 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_merge_20241221_0522'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logs',
            options={'verbose_name_plural': 'Personnel logs'},
        ),
        migrations.AlterModelOptions(
            name='roomschedule',
            options={},
        ),
        migrations.RenameField(
            model_name='roomschedule',
            old_name='room_id',
            new_name='room',
        ),
        migrations.AddField(
            model_name='room',
            name='last_checked',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='roomschedule',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roomschedule',
            name='day_of_week',
            field=models.CharField(blank=True, choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=9, null=True),
        ),
    ]
