# Generated by Django 5.1.3 on 2024-12-24 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_alter_logs_options_alter_roomschedule_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomschedule',
            old_name='supervisor',
            new_name='professor',
        ),
    ]
