# Generated by Django 5.1.3 on 2024-12-25 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_delete_temporarypersonnel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomschedule',
            name='date',
            field=models.DateField(blank=True, help_text='For one-time schedules.', null=True),
        ),
        migrations.AlterField(
            model_name='roomschedule',
            name='day_of_week',
            field=models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], help_text='For weekly recurring schedules.', max_length=9, null=True),
        ),
        migrations.AddConstraint(
            model_name='roomschedule',
            constraint=models.CheckConstraint(condition=models.Q(('start_time__gte', models.F('end_time')), _negated=True), name='start_time_before_end_time'),
        ),
    ]
