# Generated by Django 5.1.3 on 2024-12-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_alter_roomschedule_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomschedule',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roomschedule',
            name='day_of_week',
            field=models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=9, null=True),
        ),
        migrations.AddConstraint(
            model_name='roomschedule',
            constraint=models.CheckConstraint(condition=models.Q(('date__isnull', False), ('day_of_week__isnull', False), _connector='OR'), name='date_or_day_must_exist'),
        ),
    ]
