# Generated by Django 5.1.3 on 2024-12-26 16:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_room_date_room_day_of_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='last_checked',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
