# Generated by Django 5.1.3 on 2025-01-03 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_remove_room_last_checked_alter_room_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='last_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
