# Generated by Django 5.1.3 on 2025-01-03 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_room_last_checked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='last_checked',
        ),
    ]
