# Generated by Django 5.1.3 on 2025-01-03 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_remove_room_last_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
