# Generated by Django 5.1.3 on 2025-01-12 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_alter_roomschedule_professor_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomschedule',
            name='day_of_week',
        ),
    ]
