# Generated by Django 5.1.3 on 2025-01-12 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_rename_name_semester_semester_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='semester_name',
        ),
    ]
