# Generated by Django 5.1.4 on 2025-01-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0065_roomschedule_unique_schedule_per_time'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='roomschedule',
            name='unique_schedule_per_time',
        ),
        migrations.AddField(
            model_name='roomschedule',
            name='overridden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='roomschedule',
            constraint=models.UniqueConstraint(fields=('room', 'date', 'start_time', 'end_time', 'schedule_type'), name='unique_schedule_per_time_type'),
        ),
    ]
