# Generated by Django 5.1.4 on 2025-01-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0066_remove_roomschedule_unique_schedule_per_time_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='roomschedule',
            name='unique_schedule_per_time_type',
        ),
        migrations.RemoveField(
            model_name='roomschedule',
            name='date',
        ),
        migrations.AddField(
            model_name='roomschedule',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='roomschedule',
            constraint=models.UniqueConstraint(fields=('room', 'day', 'start_time', 'end_time', 'schedule_type'), name='unique_schedule_per_day_type'),
        ),
    ]
