# Generated by Django 5.1.5 on 2025-01-22 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0068_archivedroomschedulelogs_roomschedulelogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='last_motion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
